version: "3.8"

services:
  rasa:
    image: rasa/rasa:3.1.2-full
    volumes:
      - ./chatbot:/app
    command:
      - run
      - --enable-api
      - --cors
      - "*"
    ports:
      - "5005:5005"
    depends_on:
      - action_server

  action_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5055:5055"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    command: python3 app.py